### ISSUE TITLE
Searching for boxen modules?

### ISSUE THREAD

**Issue by staxmanade** [boxen/boxen.github.com#15]
Hey All,

While building out a recent boxen setup I found myself wishing there was an easier way to locate modules.

My workflow was
  - Go to [github.com/boxen](https://github.com/boxen) 
  - use the repo search to find a module
  - Open repo in a new tab
  - Go to releases page
  - Select tags

Now I have enough info to update my `Puppetfile`, but it's very manual.

If there is a better workflow, then I missed it... Would be interested in how you guys go about finding modules. In the meantime I hacked together a rough prototype of something that I think would be great to see on the boxen home page (or easily linked page from boxen home).

It's functionality is very limited and I think could be extended heavily to do more, but wanted to get some thoughts...

### Currently supports:

- [x] Loading all github.com/boxen/puppet-* modules
- [x] Search
- [x] Selecting a module loads the tags and prepares easy copy/paste `Puppetfile` and manifest include.

### Known issues:

- [ ] It's ugly :smile: (but that's why it's a prototype)
- [ ] Fixup search functionality: Searching for `hub` or `git` doesn't work because both are found in the url's of all so it won't limit correctly.
- [ ] This site is not easy on GitHub as it hits all paginated pages of the repo's api to load it's data into the browser.
- [ ] Some repo's have special instructions for installing on their readme.

### Future ideas:

- [ ] Add ability to search all of github.com for 'puppet-*' repositories.
- [ ] Load the module's readme on item selected.
- [ ] Deep linking (automatically selecting a module)

Any feedback?

**Comment by MikeMcQuaid** [comment]
Nice site but I think we'll leave it as an unofficial solution for now. Sorry!
