### ISSUE TITLE
Install command too small, and not copy & pasteable

### ISSUE THREAD

**Issue by mcandre** [boxen/boxen.github.com#16]
As a newbie, I want the fundamental install commands to be big and easy to copy & paste, like Homebrew does.

Screenshots for shell commands are bad form.

**Comment by rafaelfranca** [comment]
The command is made to be copied and paste. Could you explain better what problem do you have?

**Comment by rafaelfranca** [comment]
I mean, there is no screenshot from shell commands on boxen web page.

**Comment by mcandre** [comment]
Maybe it's a Chrome thing, but this is what I see:

http://i.imgur.com/A0mL7OH.png

And I cannot easily click, drag, copy or paste the tiny command, as I can with Homebrew, RVM, and other documentation.

**Comment by rafaelfranca** [comment]
Ah, you are in the wrong page, you are in the marketing page. If you want to use boxen in the web you have to deploy this project like explained at https://github.com/boxen/boxen-web#deployment. Also read the our-boxen README https://github.com/boxen/our-boxen.

**Comment by mcandre** [comment]
In that case, could we replace the image of tiny command line text with a link to https://github.com/boxen/our-boxen ?

**Comment by rafaelfranca** [comment]
I don't know. That is a marketing site and I believe it is good for a marketing site to show some images of the actual system. Anyway, if you think it is still worth to change it please open an issue at https://github.com/boxen/boxen.github.com
