### ISSUE TITLE
Install command too small, and not copy & pasteable

### ISSUE THREAD

**Issue by mcandre** [boxen/boxen.github.com#17]
As requested in #16, please replace the image of tiny command line text with a link to https://github.com/boxen/our-boxen. It's bad form for a public-facing tech site to use tiny screenshots of shell commands rather than PRE tags.

**Comment by rafaelfranca** [comment]
@mcandre that instructions are not be be followed. It is just an example of the actual page built with boxen-web. Is there anything in the text in that page saying to you copy and paste in your shell?

**Comment by rafaelfranca** [comment]
Maybe we should just remove that image since it tells "Run this command in your terminal".

**Comment by rafaelfranca** [comment]
@mikemcquaid mind to ask to one of GitHub designer an opinion about this? Since the marketing page still have the GitHub brand on it, I don't want to change it without a :+1: from GitHub's team.

**Comment by mikemcquaid** [comment]
I'm OK with changing or editing this image so it's more clear what's going on but I don't think it should be replaced with the suggested link.

**Comment by MikeMcQuaid** [comment]
This site has been :fire: so this can be closed.
